package com.lukrodrigotrejo.autocor.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lukrodrigotrejo.autocor.db.greendao.Marca;
import com.lukrodrigotrejo.autocor.db.greendao.Tipo_Auto;
import com.lukrodrigotrejo.autocor.db.greendao.Rubro;
import com.lukrodrigotrejo.autocor.db.greendao.Stock;
import com.lukrodrigotrejo.autocor.db.greendao.Stock_Grande;

import com.lukrodrigotrejo.autocor.db.greendao.MarcaDao;
import com.lukrodrigotrejo.autocor.db.greendao.Tipo_AutoDao;
import com.lukrodrigotrejo.autocor.db.greendao.RubroDao;
import com.lukrodrigotrejo.autocor.db.greendao.StockDao;
import com.lukrodrigotrejo.autocor.db.greendao.Stock_GrandeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig marcaDaoConfig;
    private final DaoConfig tipo_AutoDaoConfig;
    private final DaoConfig rubroDaoConfig;
    private final DaoConfig stockDaoConfig;
    private final DaoConfig stock_GrandeDaoConfig;

    private final MarcaDao marcaDao;
    private final Tipo_AutoDao tipo_AutoDao;
    private final RubroDao rubroDao;
    private final StockDao stockDao;
    private final Stock_GrandeDao stock_GrandeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        marcaDaoConfig = daoConfigMap.get(MarcaDao.class).clone();
        marcaDaoConfig.initIdentityScope(type);

        tipo_AutoDaoConfig = daoConfigMap.get(Tipo_AutoDao.class).clone();
        tipo_AutoDaoConfig.initIdentityScope(type);

        rubroDaoConfig = daoConfigMap.get(RubroDao.class).clone();
        rubroDaoConfig.initIdentityScope(type);

        stockDaoConfig = daoConfigMap.get(StockDao.class).clone();
        stockDaoConfig.initIdentityScope(type);

        stock_GrandeDaoConfig = daoConfigMap.get(Stock_GrandeDao.class).clone();
        stock_GrandeDaoConfig.initIdentityScope(type);

        marcaDao = new MarcaDao(marcaDaoConfig, this);
        tipo_AutoDao = new Tipo_AutoDao(tipo_AutoDaoConfig, this);
        rubroDao = new RubroDao(rubroDaoConfig, this);
        stockDao = new StockDao(stockDaoConfig, this);
        stock_GrandeDao = new Stock_GrandeDao(stock_GrandeDaoConfig, this);

        registerDao(Marca.class, marcaDao);
        registerDao(Tipo_Auto.class, tipo_AutoDao);
        registerDao(Rubro.class, rubroDao);
        registerDao(Stock.class, stockDao);
        registerDao(Stock_Grande.class, stock_GrandeDao);
    }
    
    public void clear() {
        marcaDaoConfig.getIdentityScope().clear();
        tipo_AutoDaoConfig.getIdentityScope().clear();
        rubroDaoConfig.getIdentityScope().clear();
        stockDaoConfig.getIdentityScope().clear();
        stock_GrandeDaoConfig.getIdentityScope().clear();
    }

    public MarcaDao getMarcaDao() {
        return marcaDao;
    }

    public Tipo_AutoDao getTipo_AutoDao() {
        return tipo_AutoDao;
    }

    public RubroDao getRubroDao() {
        return rubroDao;
    }

    public StockDao getStockDao() {
        return stockDao;
    }

    public Stock_GrandeDao getStock_GrandeDao() {
        return stock_GrandeDao;
    }

}
