package com.lukrodrigotrejo.autocor.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.lukrodrigotrejo.autocor.db.greendao.Rubro;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RUBRO".
*/
public class RubroDao extends AbstractDao<Rubro, Long> {

    public static final String TABLENAME = "RUBRO";

    /**
     * Properties of entity Rubro.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Codigo = new Property(0, Long.class, "Codigo", true, "CODIGO");
        public final static Property Descripcion = new Property(1, String.class, "Descripcion", false, "DESCRIPCION");
    };


    public RubroDao(DaoConfig config) {
        super(config);
    }
    
    public RubroDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RUBRO\" (" + //
                "\"CODIGO\" INTEGER PRIMARY KEY ," + // 0: Codigo
                "\"DESCRIPCION\" TEXT);"); // 1: Descripcion
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RUBRO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Rubro entity) {
        stmt.clearBindings();
 
        Long Codigo = entity.getCodigo();
        if (Codigo != null) {
            stmt.bindLong(1, Codigo);
        }
 
        String Descripcion = entity.getDescripcion();
        if (Descripcion != null) {
            stmt.bindString(2, Descripcion);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Rubro readEntity(Cursor cursor, int offset) {
        Rubro entity = new Rubro( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Codigo
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // Descripcion
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Rubro entity, int offset) {
        entity.setCodigo(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescripcion(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Rubro entity, long rowId) {
        entity.setCodigo(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Rubro entity) {
        if(entity != null) {
            return entity.getCodigo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }

    public Rubro getByCodigo(String codigo){
        Rubro rubro = queryBuilder().where(Properties.Codigo.eq(codigo)).unique();
        return rubro;
    }


}
