package com.lukrodrigotrejo.autocor.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RUBRO".
 */
public class Rubro {

    private Long id;
    private int Codigo;
    private String Descripcion;

    public Rubro() {
    }

    public Rubro(Long id) {
        this.id = id;
    }

    public Rubro(Long id, int Codigo, String Descripcion) {
        this.id = id;
        this.Codigo = Codigo;
        this.Descripcion = Descripcion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCodigo() {
        return Codigo;
    }

    public void setCodigo(int Codigo) {
        this.Codigo = Codigo;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

}
