package com.lukrodrigotrejo.autocor.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STOCK".
 */
public class Stock {

    private String Codigo;
    private String Marca;
    private Long Tipo_Auto;
    private Long Rubro;
    private String NroOriginal;
    private String Descripcion;
    private Double Precio;

    public Stock() {
    }

    public Stock(String Codigo) {
        this.Codigo = Codigo;
    }

    public Stock(String Codigo, String Marca, Long Tipo_Auto, Long Rubro, String NroOriginal, String Descripcion, Double Precio) {
        this.Codigo = Codigo;
        this.Marca = Marca;
        this.Tipo_Auto = Tipo_Auto;
        this.Rubro = Rubro;
        this.NroOriginal = NroOriginal;
        this.Descripcion = Descripcion;
        this.Precio = Precio;
    }

    public String getCodigo() {
        return Codigo;
    }

    public void setCodigo(String Codigo) {
        this.Codigo = Codigo;
    }

    public String getMarca() {
        return Marca;
    }

    public void setMarca(String Marca) {
        this.Marca = Marca;
    }

    public Long getTipo_Auto() {
        return Tipo_Auto;
    }

    public void setTipo_Auto(Long Tipo_Auto) {
        this.Tipo_Auto = Tipo_Auto;
    }

    public Long getRubro() {
        return Rubro;
    }

    public void setRubro(Long Rubro) {
        this.Rubro = Rubro;
    }

    public String getNroOriginal() {
        return NroOriginal;
    }

    public void setNroOriginal(String NroOriginal) {
        this.NroOriginal = NroOriginal;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public Double getPrecio() {
        return Precio;
    }

    public void setPrecio(Double Precio) {
        this.Precio = Precio;
    }

}
