package com.lukrodrigotrejo.autocor.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STOCK__GRANDE".
 */
public class Stock_Grande {

    private Long id;
    /** Not-null value. */
    private String Codigo;
    private String Descripcion;

    public Stock_Grande() {
    }

    public Stock_Grande(Long id) {
        this.id = id;
    }

    public Stock_Grande(Long id, String Codigo, String Descripcion) {
        this.id = id;
        this.Codigo = Codigo;
        this.Descripcion = Descripcion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCodigo() {
        return Codigo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodigo(String Codigo) {
        this.Codigo = Codigo;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

}
