package com.lukrodrigotrejo.autocor.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STOCK".
 */
public class Stock {

    private Long id;
    /** Not-null value. */
    private String Codigo;
    private String Marca;
    private Integer Tipo_Auto;
    private Integer Rubro;
    private String NroOriginal;
    private String Descripcion;
    private Double Precio;

    public Stock() {
    }

    public Stock(Long id) {
        this.id = id;
    }

    public Stock(Long id, String Codigo, String Marca, Integer Tipo_Auto, Integer Rubro, String NroOriginal, String Descripcion, Double Precio) {
        this.id = id;
        this.Codigo = Codigo;
        this.Marca = Marca;
        this.Tipo_Auto = Tipo_Auto;
        this.Rubro = Rubro;
        this.NroOriginal = NroOriginal;
        this.Descripcion = Descripcion;
        this.Precio = Precio;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCodigo() {
        return Codigo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodigo(String Codigo) {
        this.Codigo = Codigo;
    }

    public String getMarca() {
        return Marca;
    }

    public void setMarca(String Marca) {
        this.Marca = Marca;
    }

    public Integer getTipo_Auto() {
        return Tipo_Auto;
    }

    public void setTipo_Auto(Integer Tipo_Auto) {
        this.Tipo_Auto = Tipo_Auto;
    }

    public Integer getRubro() {
        return Rubro;
    }

    public void setRubro(Integer Rubro) {
        this.Rubro = Rubro;
    }

    public String getNroOriginal() {
        return NroOriginal;
    }

    public void setNroOriginal(String NroOriginal) {
        this.NroOriginal = NroOriginal;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public Double getPrecio() {
        return Precio;
    }

    public void setPrecio(Double Precio) {
        this.Precio = Precio;
    }

}
