package com.lukrodrigotrejo.autocor.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.lukrodrigotrejo.autocor.db.greendao.Stock;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STOCK".
*/
public class StockDao extends AbstractDao<Stock, Long> {

    public static final String TABLENAME = "STOCK";

    /**
     * Properties of entity Stock.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Codigo = new Property(1, String.class, "Codigo", false, "CODIGO");
        public final static Property Marca = new Property(2, String.class, "Marca", false, "MARCA");
        public final static Property Tipo_Auto = new Property(3, Integer.class, "Tipo_Auto", false, "TIPO__AUTO");
        public final static Property Rubro = new Property(4, Integer.class, "Rubro", false, "RUBRO");
        public final static Property NroOriginal = new Property(5, String.class, "NroOriginal", false, "NRO_ORIGINAL");
        public final static Property Descripcion = new Property(6, String.class, "Descripcion", false, "DESCRIPCION");
        public final static Property Precio = new Property(7, Double.class, "Precio", false, "PRECIO");
    };


    public StockDao(DaoConfig config) {
        super(config);
    }
    
    public StockDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STOCK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CODIGO\" TEXT NOT NULL UNIQUE ," + // 1: Codigo
                "\"MARCA\" TEXT," + // 2: Marca
                "\"TIPO__AUTO\" INTEGER," + // 3: Tipo_Auto
                "\"RUBRO\" INTEGER," + // 4: Rubro
                "\"NRO_ORIGINAL\" TEXT," + // 5: NroOriginal
                "\"DESCRIPCION\" TEXT," + // 6: Descripcion
                "\"PRECIO\" REAL);"); // 7: Precio
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STOCK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Stock entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCodigo());
 
        String Marca = entity.getMarca();
        if (Marca != null) {
            stmt.bindString(3, Marca);
        }
 
        Integer Tipo_Auto = entity.getTipo_Auto();
        if (Tipo_Auto != null) {
            stmt.bindLong(4, Tipo_Auto);
        }
 
        Integer Rubro = entity.getRubro();
        if (Rubro != null) {
            stmt.bindLong(5, Rubro);
        }
 
        String NroOriginal = entity.getNroOriginal();
        if (NroOriginal != null) {
            stmt.bindString(6, NroOriginal);
        }
 
        String Descripcion = entity.getDescripcion();
        if (Descripcion != null) {
            stmt.bindString(7, Descripcion);
        }
 
        Double Precio = entity.getPrecio();
        if (Precio != null) {
            stmt.bindDouble(8, Precio);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Stock readEntity(Cursor cursor, int offset) {
        Stock entity = new Stock( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // Codigo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Marca
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // Tipo_Auto
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // Rubro
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // NroOriginal
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Descripcion
            cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7) // Precio
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Stock entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCodigo(cursor.getString(offset + 1));
        entity.setMarca(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTipo_Auto(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setRubro(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setNroOriginal(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDescripcion(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPrecio(cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Stock entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Stock entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
